// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/shoes-agent.proto

package shoesagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// type
type Status int32

const (
	Status_Unknown Status = 0
	Status_Booting Status = 1
	Status_Idle    Status = 2
	Status_Active  Status = 3
	Status_Offline Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Unknown",
		1: "Booting",
		2: "Idle",
		3: "Active",
		4: "Offline",
	}
	Status_value = map[string]int32{
		"Unknown": 0,
		"Booting": 1,
		"Idle":    2,
		"Active":  3,
		"Offline": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_shoes_agent_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_shoes_agent_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_shoes_agent_proto_rawDescGZIP(), []int{0}
}

// req / resp
type GetAgentStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shoes_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shoes_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_shoes_agent_proto_rawDescGZIP(), []int{0}
}

type GetAgentStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=shoesagent.Status" json:"status,omitempty"`
}

func (x *GetAgentStatusResponse) Reset() {
	*x = GetAgentStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shoes_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusResponse) ProtoMessage() {}

func (x *GetAgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shoes_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_shoes_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Unknown
}

type StartRunnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetupScript string `protobuf:"bytes,1,opt,name=setup_script,json=setupScript,proto3" json:"setup_script,omitempty"`
}

func (x *StartRunnerRequest) Reset() {
	*x = StartRunnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shoes_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRunnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunnerRequest) ProtoMessage() {}

func (x *StartRunnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shoes_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunnerRequest.ProtoReflect.Descriptor instead.
func (*StartRunnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_shoes_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StartRunnerRequest) GetSetupScript() string {
	if x != nil {
		return x.SetupScript
	}
	return ""
}

type StartRunnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartRunnerResponse) Reset() {
	*x = StartRunnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shoes_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRunnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunnerResponse) ProtoMessage() {}

func (x *StartRunnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shoes_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunnerResponse.ProtoReflect.Descriptor instead.
func (*StartRunnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_shoes_agent_proto_rawDescGZIP(), []int{3}
}

var File_proto_shoes_agent_proto protoreflect.FileDescriptor

var file_proto_shoes_agent_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x65, 0x73, 0x2d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x68, 0x6f, 0x65, 0x73,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x68, 0x6f, 0x65, 0x73,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x37, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65,
	0x74, 0x75, 0x70, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x74, 0x75, 0x70, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x45, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x42,
	0x6f, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x64, 0x6c, 0x65,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x04, 0x32, 0xb9, 0x01, 0x0a, 0x0a,
	0x53, 0x68, 0x6f, 0x65, 0x73, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x2e, 0x73,
	0x68, 0x6f, 0x65, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x73, 0x68, 0x6f, 0x65, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75,
	0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x73, 0x68, 0x6f, 0x65, 0x73, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x68, 0x6f, 0x65, 0x73, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x68, 0x79, 0x77, 0x61, 0x69, 0x74, 0x61, 0x2f, 0x73,
	0x68, 0x6f, 0x65, 0x73, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x67, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x65, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_shoes_agent_proto_rawDescOnce sync.Once
	file_proto_shoes_agent_proto_rawDescData = file_proto_shoes_agent_proto_rawDesc
)

func file_proto_shoes_agent_proto_rawDescGZIP() []byte {
	file_proto_shoes_agent_proto_rawDescOnce.Do(func() {
		file_proto_shoes_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shoes_agent_proto_rawDescData)
	})
	return file_proto_shoes_agent_proto_rawDescData
}

var file_proto_shoes_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_shoes_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shoes_agent_proto_goTypes = []interface{}{
	(Status)(0),                    // 0: shoesagent.Status
	(*GetAgentStatusRequest)(nil),  // 1: shoesagent.GetAgentStatusRequest
	(*GetAgentStatusResponse)(nil), // 2: shoesagent.GetAgentStatusResponse
	(*StartRunnerRequest)(nil),     // 3: shoesagent.StartRunnerRequest
	(*StartRunnerResponse)(nil),    // 4: shoesagent.StartRunnerResponse
}
var file_proto_shoes_agent_proto_depIdxs = []int32{
	0, // 0: shoesagent.GetAgentStatusResponse.status:type_name -> shoesagent.Status
	1, // 1: shoesagent.ShoesAgent.GetAgentStatus:input_type -> shoesagent.GetAgentStatusRequest
	3, // 2: shoesagent.ShoesAgent.StartRunner:input_type -> shoesagent.StartRunnerRequest
	2, // 3: shoesagent.ShoesAgent.GetAgentStatus:output_type -> shoesagent.GetAgentStatusResponse
	4, // 4: shoesagent.ShoesAgent.StartRunner:output_type -> shoesagent.StartRunnerResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shoes_agent_proto_init() }
func file_proto_shoes_agent_proto_init() {
	if File_proto_shoes_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shoes_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shoes_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shoes_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRunnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shoes_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRunnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shoes_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shoes_agent_proto_goTypes,
		DependencyIndexes: file_proto_shoes_agent_proto_depIdxs,
		EnumInfos:         file_proto_shoes_agent_proto_enumTypes,
		MessageInfos:      file_proto_shoes_agent_proto_msgTypes,
	}.Build()
	File_proto_shoes_agent_proto = out.File
	file_proto_shoes_agent_proto_rawDesc = nil
	file_proto_shoes_agent_proto_goTypes = nil
	file_proto_shoes_agent_proto_depIdxs = nil
}
