name: Test
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        target:
          - agent
          - shoes-agent-mock
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: |
          cd ${{ matrix.target }}
          go build .
      - name: Lint
        run: |
          cd ${{ matrix.target }}
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
      - name: vet
        run: |
          cd ${{ matrix.target }}
          go vet ./...
      - name: Test
        run: |
          cd ${{ matrix.target }}
          go test -v ./...
  test-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: ./proto.sh

